common_args:
  training_type: "simulation"
  random_seed: 0
data_args:
  dataset: "cifar10"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
model_args:
  model: "resnet56"
train_args:
  federated_optimizer: "HierarchicalFL"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 90
  comm_round: 100000
  time_budget: 4000
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  group_method: "hetero"
  group_alpha: 0.01
  group_num: 9
  group_comm_round: 5
  group_comm_pattern: "decentralized"
  topo_name: "ring"
  topo_edge_probability: 1.0
ns3_args:
  enable_parameter_estimation: False
  enable_ns3: True
  fast_mode: True
  underlay: 'geantdistance'
  access_link_capacity: 1.0e+7
  core_link_capacity: 1.0e+9
  lan_capacity: 1.0e+11
  local_update_time: 0.07576
validation_args:
  frequency_of_the_test: 5
device_args:
  worker_num: 10
  using_gpu: true
  gpu_mapping_file: config/cifar10_resnet56/gpu_mapping.yaml
  gpu_mapping_key: mapping_config1_10
comm_args:
  backend: "MPI"
  is_mobile: 0
tracking_args:
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: cpfedavg
  run_name: mpi_hierarchical_fl_cifar10_resnet56
  wandb_only_server: true
